### PR TITLE
Update for TileDB 1.7.0 release

### PR DESCRIPTION
**Pull request by Shelnutt2**
Update for TileDB 1.7.0 release

### CODE REVIEW

**Review by tdenniston — APPROVED** [review]
Thanks @Shelnutt2

**Review by ihnorton — APPROVED** [review]
Tested locally (build and `brew test ./tiledb.rb`), LGTM

**Comment by ihnorton** [comment]
Not sure if I missed something up by deleting the branch (now restored) -- the internal instructions say not to delete the branch, although the naming is different than the suggestion there. I don't know how this interacts with homebrew upstream.

**Comment by tdenniston** [comment]
Just did a `brew update` on my mac and I am seeing 
```
$ brew info tiledb
tiledb-inc/stable/tiledb: stable 1.7.0, HEAD
```
so I think it should be good.

**Pull request merged**
