### PR TITLE
Enable serialization by default

### PR DESCRIPTION
**Pull request by Shelnutt2**
Add option to disable serialization.

Also bump TileDB to 1.6.2.

Note this is untested, I'm not sure how to test brew.

### CODE REVIEW

**Comment by tdenniston** [comment]
You'll need to invert the serialization test in travis as well, since the flag changed.

**Comment by tdenniston** [comment]
@ihnorton I am not too familiar with brew packaging, so could you also take a look?

**Comment by Shelnutt2** [comment]
> You'll need to invert the serialization test in travis as well, since the flag changed.

Good catch, thanks.

**Review by ihnorton — APPROVED** [review]
I don't have much experience with homebrew dev, but looks ok. Successful local build on this branch.

**Comment by tdenniston** [comment]
Subsumed by #26

**Pull request closed without merging**
