### PR TITLE
Update to TileDB 2.2.5

### PR DESCRIPTION
**Pull request by Shelnutt2**
Update to TileDB 2.2.5

### CODE REVIEW

**Comment by ihnorton** [comment]
(looks like CI stalled - reopening to rerun)

**Comment by aaronwolen** [comment]
@ihnorton, do we need to run `brew update` every time?

**Comment by ihnorton** [comment]
Updated to 2.2.7, let's see CI..

**Comment by Shelnutt2** [comment]
Closing in favor of #46

**Pull request closed without merging**
